// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC24Ivxgedic2RzPGVJPQL8mbIhnjO61i8',
    appId: '1:5881658993:web:f4a311ca450ccc613be5d0',
    messagingSenderId: '5881658993',
    projectId: 'e-comers-b44f8',
    authDomain: 'e-comers-b44f8.firebaseapp.com',
    storageBucket: 'e-comers-b44f8.appspot.com',
    measurementId: 'G-KC6X25N9C9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoBXdWHeg6yekJ0vTkDgSOgeOqK3luomU',
    appId: '1:5881658993:android:fc3beec047d38a563be5d0',
    messagingSenderId: '5881658993',
    projectId: 'e-comers-b44f8',
    storageBucket: 'e-comers-b44f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnd_hyCoyoDuR5saKUg9I0fTDZMZMWWOA',
    appId: '1:5881658993:ios:a58ce63c8e222d103be5d0',
    messagingSenderId: '5881658993',
    projectId: 'e-comers-b44f8',
    storageBucket: 'e-comers-b44f8.appspot.com',
    iosBundleId: 'com.example.eCommers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnd_hyCoyoDuR5saKUg9I0fTDZMZMWWOA',
    appId: '1:5881658993:ios:a58ce63c8e222d103be5d0',
    messagingSenderId: '5881658993',
    projectId: 'e-comers-b44f8',
    storageBucket: 'e-comers-b44f8.appspot.com',
    iosBundleId: 'com.example.eCommers',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC24Ivxgedic2RzPGVJPQL8mbIhnjO61i8',
    appId: '1:5881658993:web:0aa4d9f52a64d1c73be5d0',
    messagingSenderId: '5881658993',
    projectId: 'e-comers-b44f8',
    authDomain: 'e-comers-b44f8.firebaseapp.com',
    storageBucket: 'e-comers-b44f8.appspot.com',
    measurementId: 'G-Z91NSTH845',
  );
}
